baseURL = 'https://msteinha.github.io/Sesselwerkstatt/'
languageCode = 'en-us'
defaultContentLanguage = 'de'
title = 'Sesselwerkstatt'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projekte"
    url = "/pages/gallery"
    weight = 2

  [[menu.main]]
    name = "Kontakt"
    url = "/pages/contact"
    weight = 3

[params]
    mainSections = ["posts"]
    description = "Wiener Geflecht - Bespannung: in Handarbeit und mit hochwertigen Materialien werden alte Möbel zu neuem Leben erweckt."