baseURL = 'https://example.org/'
languageCode = 'en-us'
defaultContentLanguage = 'de'
title = 'Sesselwerkstatt'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
    mainSections = ["posts"]