baseURL = 'https://msteinha.github.io/Sesselwerkstatt/'
languageCode = 'en-us'
defaultContentLanguage = 'de'
title = 'Sesselwerkstatt'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projekte"
    url = "/pages/gallery"
    weight = 2

  [[menu.main]]
    name = "Kontakt"
    url = "/pages/contact"
    weight = 3

[params]
    mainSections = ["posts"]